import { Audit, Finding } from '../types/schema';

/**
 * Generates a clean, structured Markdown remediation report string
 */
export function generateMarkdownReport(audit: Audit, findings: Finding[]): string {
  const dateStr = new Date(audit.createdAt).toLocaleString('en-US');
  const before = audit.violationsBefore;
  const after = audit.violationsAfter !== null ? audit.violationsAfter : before;
  const reduction = before > 0 ? Math.round(((before - after) / before) * 100) : 0;

  const verifiedFindings = findings.filter((f) => f.status === 'verified');
  const humanFindings = findings.filter((f) => f.requiresHumanInput);
  const detectedFindings = findings.filter((f) => f.status === 'detected');

  let md = `# A11ySentinel — Accessibility Remediation Report

> **Audit ID:** \`${audit.auditId}\`  
> **Target URL:** [${audit.targetUrl}](${audit.targetUrl})  
> **Date:** ${dateStr}  
> **Pages Audited:** ${audit.pageCount}  
> **Audit Status:** \`${audit.status}\`

---

## 1. Executive Summary & Impact Metrics

* **Measured axe-core Violations Before:** \`${before}\`
* **Measured axe-core Violations After:** \`${after}\`
* **Net Reduction Rate:** **-${reduction}%**
* **Verified Source-Level Patches:** **${verifiedFindings.length}**
* **Action Required Items (Human Review):** **${humanFindings.length}**

> **Claim Discipline & Integrity Disclaimer:**  
> A11ySentinel finds, prioritises, drafts, and verifies accessibility fixes under human review. It produces mergeable source-level code diffs. It is **not** a client-side runtime overlay widget and does not claim automatic 100% legal compliance.

---

## 2. Technical Standard & Scope

* **Primary Global Standard:** **WCAG 2.1 AA** (Web Content Accessibility Guidelines)
* **Regional Reference Framework:** ${findings.find(f => f.regionalFramework)?.regionalFramework || 'RGAA 4 (Contextual cross-reference)'}
* **Evaluation Engine:** \`axe-core 4.10.2\` (Deterministic ground truth) & \`Gemini 3.7 Flash\` (Multimodal visual audit)

---

## 3. Verified Source-Level Fixes (${verifiedFindings.length})

The following patches have been applied to the DOM and verified by re-running axe-core with zero regressions.

`;

  verifiedFindings.forEach((f, idx) => {
    md += `### ${idx + 1}. [${f.severity.toUpperCase()}] ${f.category} — \`WCAG ${f.wcagCriterion}\`${f.regionalFramework && f.regionalCriterion ? ` / \`${f.regionalFramework} ${f.regionalCriterion}\`` : ''}

* **Finding ID:** \`${f.findingId}\`
* **Page URL:** [${f.pageUrl}](${f.pageUrl})
* **Source:** \`${f.source}\` (Confidence: ${(f.confidence * 100).toFixed(0)}%)
* **User Impact:** ${f.userImpact}
${f.evidence ? `* **Multimodal Visual Evidence:** ${f.evidence}\n` : ''}* **CSS Selector:** \`${f.selector}\`
${f.changeSummary ? `* **Change Summary:** *"${f.changeSummary}"*\n` : ''}`;

    if (f.announcedBefore !== null && f.announcedAfter !== null) {
      md += `
**Screen Reader Announcement Comparison (Chromium CDP):**
* **Before Patch:** \`${f.announcedBefore}\`
* **After Patch:** \`${f.announcedAfter}\`
`;
    }

    if (f.patchedCode) {
      md += `
**Verified Source Code Diff:**
\`\`\`html
- ${f.currentCode}
+ ${f.patchedCode}
\`\`\`
`;
    }

    md += `\n---\n\n`;
  });

  if (humanFindings.length > 0) {
    md += `## 4. Action Required — Human Author Review (${humanFindings.length})

The following findings require a human content author or editor to supply specific context (such as image descriptions or business intent). Explicit \`TODO\` placeholders have been inserted into the code patches.

`;

    humanFindings.forEach((f, idx) => {
      md += `### ${idx + 1}. [${f.severity.toUpperCase()}] ${f.category} — \`WCAG ${f.wcagCriterion}\`

* **Finding ID:** \`${f.findingId}\`
* **CSS Selector:** \`${f.selector}\`
* **Editorial Guidance:** ${f.humanGuidance}
* **Generated Patch:**
\`\`\`html
${f.patchedCode}
\`\`\`

---

`;
    });
  }

  if (detectedFindings.length > 0) {
    md += `## 5. Detected Violations Pending Patch Verification (${detectedFindings.length})

The following issues were confirmed by axe-core but have not yet received a verified code patch.

`;

    detectedFindings.forEach((f, idx) => {
      md += `* **[${f.severity.toUpperCase()}] \`WCAG ${f.wcagCriterion}\` ${f.category}:** ${f.userImpact} (Selector: \`${f.selector}\`)\n`;
    });

    md += `\n---\n\n`;
  }

  md += `*Report generated by A11ySentinel — Autonomous Accessibility Remediation Agent.*
`;

  return md;
}

/**
 * Triggers a client-side file download of the Markdown report
 */
export function downloadMarkdownFile(audit: Audit, findings: Finding[]): void {
  const content = generateMarkdownReport(audit, findings);
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `A11ySentinel_Remediation_Report_${audit.auditId}.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
